### ISSUE TITLE
nornir.core.exceptions.PluginNotRegistered: plugin 'nornir_utils.plugins.inventory.yaml_inventory' is not registered

### ISSUE THREAD

**Issue by jblokesh** [veprimk/csv2nornir_inventory#2]
Hi,
I am using exactly same code, without any change and it is successfully creating the Inventory file but I am also getting this error.

Inventory file created...
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.25.8) or chardet (4.0.0) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Traceback (most recent call last):
  File "/home/admin123/Jnyanesh_Automation/nornir_inventory.py", line 13, in <module>
    nr = InitNornir(inventory={"plugin": "nornir_utils.plugins.inventory.yaml_inventory", "options": {"host_file": "csv_inventory.yaml"}})
  File "/home/admin123/.local/lib/python3.8/site-packages/nornir/init_nornir.py", line 64, in InitNornir
    inventory=load_inventory(config),
  File "/home/admin123/.local/lib/python3.8/site-packages/nornir/init_nornir.py", line 17, in load_inventory
    inventory_plugin = InventoryPluginRegister.get_plugin(config.inventory.plugin)
  File "/home/admin123/.local/lib/python3.8/site-packages/nornir/core/plugins/register.py", line 75, in get_plugin
    raise PluginNotRegistered(f"plugin {name!r} is not registered")
nornir.core.exceptions.PluginNotRegistered: plugin 'nornir_utils.plugins.inventory.yaml_inventory' is not registered

**Comment by veprimk** [comment]
@jblokesh I think the new version of Nornir has changed the way the Inventory file is loaded and is done through the Simple Inventory Plugin. You might want to create a file called **nornir.yaml** similar to this one [https://github.com/nornir-automation/nornir-tools/blob/master/examples/network/get_facts/nornir.yaml](url). Please also check out the example provided by Nornirn maintainers [https://github.com/nornir-automation/nornir-tools/blob/master/examples/network/get_facts/](url).

**Comment by jnyany** [comment]
Thanks @veprimk  I already tried that. It is successfully creating the new inventory, hosts.yaml but this error is not going away.
nornir.core.exceptions.PluginNotRegistered: plugin 'nornir_utils.plugins.inventory.yaml_inventory' is not registered

I even tried to register plugin, using this page https://nornir.readthedocs.io/en/latest/plugins/index.html
but this documentation like where to do this steps is not clear to me.

**Comment by veprimk** [comment]
@jnyany closing this as it's not a code issue.
